### ISSUE TITLE
css stylesheet  needs to be updated in v3.0.6-qa.3 build

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#157]
Just noticed that in build  Alpheios Reading Tools 3.0.6.99
Alpheios Components 1.6.3-dev  we are again missing the space in the morphology lookup
e.g. personsing
see attachment
![personsing](https://user-images.githubusercontent.com/41396793/74158820-bdfa1300-4be8-11ea-8d0f-0ce7280e8061.JPG)

**Comment by monzug** [comment]
we did also lost the style for the verbs.  see attachment

![Screen Shot 2020-02-16 at 6 26 30 PM](https://user-images.githubusercontent.com/41396793/74609400-fd919500-50e9-11ea-8934-f29cd41263e7.png)

**Comment by balmas** [comment]
I think this is fallout from https://github.com/alpheios-project/components/pull/894

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200309431

**Comment by monzug** [comment]
both issues reported upthere are still reproducible in build  Alpheios Reading Tools 3.1.0 build qa.20200309459
Alpheios Components 3.3.0-qa.20200309431 build qa.20200309431 
tested in FF

**Comment by balmas** [comment]
@irina060981 can you take another look at this? Thanks!

**Comment by monzug** [comment]
one more in Chrome
![short-def](https://user-images.githubusercontent.com/41396793/76338016-87d6ae80-62ce-11ea-94b9-3bdd42266ecb.JPG)

**Comment by irina060981** [comment]
>we did also lost the style for the verbs. see attachment

I didn't see the problems with styles in inflections, but according to the old version in https://texts.alpheios.net/
inflection table for latin irregular verbs are broken

![image](https://user-images.githubusercontent.com/12377640/76590875-4b0eef80-653a-11ea-9dfb-a60de75b0d9a.png)

@monzug , do you mean this problem?

**Comment by monzug** [comment]
Irina, here is a screenshot in build Alpheios Reading Tools 3.1.0 build qa.20200309459
Alpheios Components 3.3.0-qa.20200309431 build qa.20200309431
![verb-latin-irreg](https://user-images.githubusercontent.com/41396793/76596697-38ae9a80-64d5-11ea-9406-3353408991bd.JPG)

**Comment by irina060981** [comment]
Monica, I am sorry - but I don't see here styles problems.
I see a lot of word forms instead of only useful. Will check this bug.

**Comment by monzug** [comment]
uhm, if this one is not stylesheet it might be something else. we have had this problem few times in the past. can you search on GitHub to see how it was fixed? 
anyhow, do you see the other problems mentioned above in recent builds?

**Comment by irina060981** [comment]
>uhm, if this one is not stylesheet it might be something else. we have had this problem few times in the past. can you search on GitHub to see how it was fixed?

Bridget has created a separate issue for this problem.

For styles - I have fixed and published to PR styles for
 - select in options
 - for tooltips padding

And I was able to reproduce padding problem the following:
![image](https://user-images.githubusercontent.com/12377640/76621779-ed02fc00-657b-11ea-8b95-c9fc21575343.png)

will fix

**Comment by irina060981** [comment]
Fixed, merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200320403

**Comment by monzug** [comment]
uhm, I do still see the problem in build qa.20200320411 - see attachments

![Screen Shot 2020-03-23 at 3 54 56 PM](https://user-images.githubusercontent.com/41396793/77330053-16abe800-6d1f-11ea-9030-ca2f7f9978c4.png)

![Screen Shot 2020-03-23 at 3 53 11 PM](https://user-images.githubusercontent.com/41396793/77330061-1875ab80-6d1f-11ea-8693-a632e68f008d.png)

**Comment by irina060981** [comment]
I don't see the upper problem - neuter**noun**, may be it is some problems with cache?

But the down part is reproducable - good catch, @monzug !
This I have fixed

![image](https://user-images.githubusercontent.com/12377640/77728475-4d983b80-7048-11ea-9f0f-8a90cf4bc1a9.png)

![image](https://user-images.githubusercontent.com/12377640/77728493-5557e000-7048-11ea-8126-08b8a83304f5.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
stilling having trouble with this one.

**Comment by balmas** [comment]
I think this should finally be fixed now in Alpheios Reading Tools 3.1.0 build qa.20200410484

**Comment by monzug** [comment]
can we improve the spacing between the tenses?
see release vs latest build

![Screen Shot 2020-04-22 at 2 28 58 PM](https://user-images.githubusercontent.com/41396793/79981956-cf438380-84a5-11ea-8071-93a993ff01bd.png)

![Screen Shot 2020-04-22 at 2 28 47 PM](https://user-images.githubusercontent.com/41396793/79981959-d10d4700-84a5-11ea-8db3-f669a4ed5600.png)

**Comment by balmas** [comment]
@kirlat since we were just talking about spacing issues, I'm going to ask you to take a look at this one. Thanks!

**Comment by balmas** [comment]
another problem with styles -- the grammar links aren't in the link color anymore
this style probably needs more specificity

**Comment by monzug** [comment]
all links do not have the color as per release

**Comment by kirlat** [comment]
Should be solved with #264.

**Comment by monzug** [comment]
@kirlat  looks good to me. we have the colors and the spacing back. I haven't fully tested fully as it hasn't been assigned to me yet.

**Comment by balmas** [comment]
oops, missed giving this back to you @monzug  :-)

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200423418

**Comment by monzug** [comment]
by comparing release with current build, I noticed that feminine is also highlighted next to noun.
lookup for romae, you'll notice that feminine is also highlighted.

**Comment by balmas** [comment]
![Screenshot from 2020-04-27 09-33-21](https://user-images.githubusercontent.com/644870/80378109-2bbdee80-886a-11ea-8751-ab095492c610.png)

![Screenshot from 2020-04-27 09-33-04](https://user-images.githubusercontent.com/644870/80378187-48f2bd00-886a-11ea-9750-ce55229bd179.png)

Yes, you're right. @kirlat the problematic style is this one:

```
.alpheios-content .alpheios-morph-data__morphdata .alpheios-morph-data__pofs, .alpheios-content .alpheios-morph-data__morphdata .alpheios-morph__linkedattr {
    cursor: pointer;
    font-weight: 700;
    color: #185F6D;
}
```
It's being applied to this element, which is a child of the element with class .alpheios-morph-data__pofs

```
<span data-feature="gender" data-grouplevel="0" class="alpheios-morph__attr">feminine masculine</span>
```

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
all good. did you add extra space between the searched word and the result? @balmas, if it's ok, I will be happy to verify this one.

![extra-space](https://user-images.githubusercontent.com/41396793/81704632-0ae5c380-943c-11ea-9546-286288cf9e2a.JPG)

**Comment by balmas** [comment]
hmm not sure about the extra space, but you can verify this one and open a new issue for that :-)

**Comment by monzug** [comment]
sure. will do.
