### ISSUE TITLE
Persian lookup bug

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios-core#165]
>lookup (change language to Persian from drop-down and enter جان    check that the word is entered from right to left in the lookup field and that in the morphology popup its meaning is father or soul. close popup)

There is a problem with Persian language - a lookup (from lookup input) produces result only after the second or third lookup (in any browser).
It is a well-known problem, but I am not sure that I should define to lookup three times to get the result.

_Originally posted by @irina060981 in https://github.com/alpheios-project/selenium-tests/issues/5#issuecomment-589574479_

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200309431

**Comment by monzug** [comment]
tested few times on chrome. when I lookup for جان , it takes sometimes (few seconds) before generating the definitions. in the meantime it does still display the message morphological data not found. so it does work somehow but t would be great if we can speed up the display of the definitions. is it possible?

**Comment by balmas** [comment]
@monzug it is super fast for me after the first lookup, which makes sense to me because with the first lookup it needs to load the entire index file, but after that it should be a quick lookup in memory for it and any other persian word. I'm puzzled why it would be slow for you. I am not thrilled with the morphological data message displaying but can live with it for now.

**Comment by monzug** [comment]
it's the first lookup that is super slow. any subsequential lookup is fast. if this is ok, I can close this one

**Comment by monzug** [comment]
see screenshots of the popups on first lookup for جان 
![persian-2](https://user-images.githubusercontent.com/41396793/76526462-ee310d80-6443-11ea-8cac-557072bcced7.JPG)
![IMG_4372](https://user-images.githubusercontent.com/41396793/76526545-13be1700-6444-11ea-847f-221f20af12a0.jpg)

**Comment by balmas** [comment]
it seems like there are still some timing issues with the notifications.  We might also need to increase the timeout on the initial request. Giving back to @irina060981 to see what she thinks.

**Comment by irina060981** [comment]
Fixed, merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200320403

**Comment by monzug** [comment]
I don't get anymore the message جان not found in our Persian resources in the morphology pop-up. However I do still experience the message reported in the first screenshot above.
anything to improve this?

**Comment by balmas** [comment]
@monzug do you mean the Lexical Query produced no results message?

**Comment by monzug** [comment]
yes. it's up there for sometimes before generating the morpholofy pop-up

**Comment by balmas** [comment]
I don't think there is much we can do about this right now. After the first lookup it should be better.  Eventually we would like to optimize the way all of the short definition and full definition queries work but until then I think this is the best we can do.
