### ISSUE TITLE
header shrink in pop-up for syriac site

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#453]
tested in Safari
Related to #417 
morphology pop-up for syriac words such as   ܡܘܗܒܬܐ
or for lookup word such as caro in the sedra site http://sedra.bethmardutho.org/library
have the header shrink after generating the pop-up
see screenshots
![Screen Shot 2020-06-12 at 2 27 02 PM](https://user-images.githubusercontent.com/41396793/84502551-d5d9c480-acb8-11ea-884c-6890a64cab0b.png)
![Screen Shot 2020-06-12 at 2 26 43 PM](https://user-images.githubusercontent.com/41396793/84502556-d83c1e80-acb8-11ea-9053-78c9023fa19d.png)

**Comment by monzug** [comment]
actually, I just saw it on the texts site too. It could be related to the size of the pop-up
![Screen Shot 2020-06-12 at 2 42 28 PM](https://user-images.githubusercontent.com/41396793/84503912-58638380-acbb-11ea-98e9-a1a61c55e342.png)

**Comment by balmas** [comment]
@kirlat is this maybe related to the change you made for #417?

**Comment by kirlat** [comment]
It might be, I will check

**Comment by kirlat** [comment]
A fix has been merged to master.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200612448
Alpheios Components 3.3.0-qa.20200612442

**Comment by monzug** [comment]
still reproducible in latest build Alpheios Embedded Library 3.1.6-qa.20200527420
Alpheios Components 3.3.0-qa.20200612442 (sedra site and text env on Safari)
1) in text env, double click on ire
![Screen Shot 2020-06-15 at 3 11 48 PM](https://user-images.githubusercontent.com/41396793/84661473-b17d2280-af1a-11ea-86a2-564b6373f864.png)
2) in http://sedra.bethmardutho.org/library, double click on  ܪܘܚܐ 
![Screen Shot 2020-06-15 at 3 05 51 PM](https://user-images.githubusercontent.com/41396793/84661615-e25d5780-af1a-11ea-92d2-7c7962e29571.png)

**Comment by balmas** [comment]
I need to check to make sure the build actually included the new css...it's possible that only changes to css and no code didn't get picked up properly.

**Comment by monzug** [comment]
could be

**Comment by balmas** [comment]
yes I think this is a build problem. Investigating..

**Comment by kirlat** [comment]
I agree, I did a test on texts-test.alpheios.net and the word has a bottom margin only:
![image](https://user-images.githubusercontent.com/18631055/84664296-60c3f480-af2f-11ea-9fca-ae24f46eb914.png)

In an updated CSS it must have both top and bottom margins, along with other changes:
![image](https://user-images.githubusercontent.com/18631055/84664379-83560d80-af2f-11ea-8202-bc03609b1ae8.png)

**Comment by balmas** [comment]
yeah it's my fault. It seems I didn't actually merge the master changes into qa before doing the build :-(

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200615315
Alpheios Components 3.3.0-qa.20200615292

Ok, let's try this again :-)

**Comment by monzug** [comment]
there is still a small adjustment in pop-up but it's almost unnoticeable
