### ISSUE TITLE
add conjugation table for odeo

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#47]
see issue alpheios-project/inflection-tables#127

**Comment by monzug** [comment]
can't find any table for odeo in any grammars... will use adeo as a base and check the ending in whitaker

**Comment by monzug** [comment]
added infinitive, imperative and irregular verb to forms.csv

**Comment by balmas** [comment]
The table should be there for matching in qa.20200723472 but it still needs to be added to the inflection browser.

**Comment by balmas** [comment]
now it's in the browser.

Alpheios Reading Tools 3.3.1 build qa.20200803307
Alpheios Components 3.3.0-qa.20200803296

**Comment by monzug** [comment]
there is a problem with the passive irregular verbs, we are missing the voice from the inflection table. The passive forms are merged with the active ones. e.g. fero, odeo, adeo.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200804636
Alpheios Components 3.3.0-qa.20200804505

The tables for fero and adeo were correct, as far as I can tell, but odeo was missing the voice.

**Comment by monzug** [comment]
the voice for odeo, fero and adeo is still missing in the browse inflection tables.
see screenshot
![voice-missing](https://user-images.githubusercontent.com/41396793/89414503-80d68f80-d6f8-11ea-9c91-3edd47943707.JPG)

**Comment by balmas** [comment]
oh! I missed that it was in the browse inflection tables. sorry!

**Comment by monzug** [comment]
the voice was missing in both. now it's only missing in the browse inflection tables.

**Comment by balmas** [comment]
should be fixed in 
webextension qa.20200807379 
components qa.20200807247

**Comment by monzug** [comment]
still missing th evoice for fero, adeo, odeo in the browse inflection tables

**Comment by balmas** [comment]
that's weird. My commit seems to have gotten lost :-( will fix again

**Comment by monzug** [comment]
well, we are in 2020... anything is possible!

**Comment by balmas** [comment]
trying again...

Alpheios Reading Tools 3.3.1 build qa.20200807525
Alpheios Components 3.3.0-qa.20200807377

**Comment by monzug** [comment]
this is fixed in   Alpheios Reading Tools 3.3.1 build qa.20200807525
Alpheios Components 3.3.0-qa.20200807377
